name: Deploy Astro to Bunny.net

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # This ensures you use a supported version
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build Astro site
        run: npm run build

      - name: Deploy to Bunny.net
        uses: R-J-dev/bunny-deploy@main
        with:
          access-key: ${{ secrets.BUNNY_API_KEY }}
          directory-to-upload: "./dist"
          storage-zone-name: "mooyo"
          storage-zone-password: ${{ secrets.BUNNY_STORAGE_PASSWORD }}
          storage-endpoint: "https://storage.bunnycdn.com"
          pull-zone-id: "5640984"
          concurrency: 50
          enable-purge-pull-zone: true
